### ISSUE TITLE
pull to refresh demo

### ISSUE THREAD

**Issue by beikege** [egonelbre/expgio#3]
Hello, @egonelbre
I'm learning GIO. I'm trying to implement the common pull-to-refresh feature for mobile using layout.List, and I'm finding it quite challenging. Could you provide a demo? Thank you.

**Comment by egonelbre** [comment]
The best places to ask these questions are either on https://lists.sr.ht/~eliasnaur/gio or `#gioui` channel on [Gophers Slack](https://invite.slack.golangbridge.org/). You are much more likely to reach people who have already implemented it. So, I recommend asking there as well.

This repository is more of my own experiments for gio. And I occasionally use it to show how to do things. I'll see whether I can think of something next week, but no promises.

**Comment by beikege** [comment]
Thank you very much for taking your precious time.

**Comment by beikege** [comment]
The current functionality cannot be implemented because the Grabbed is always exclusive. I consulted Elias Naur, and his suggestion is:

`I believe the viable solution is to enhance layout.List with an 'overscroll' feature that tells you how far a user has scrolled outside either end. For example, it could be a new struct field at l.list.Position.Overscroll. For now, you can copy layout.List and add the feature yourself. We'll also be happy to see a patch or PR so the feature can be added to the public code.`

Sorry, I posted the question in the wrong place. I will close it.
